[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
extra_assets = "AGGtK3Vzo8k5JFqmrmrDnGPwzGzUzenyUw6tbtDUbi84"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/lt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
